require('ramedlawH.autocompletion')
require('ramedlawH.nvim-autopairs')
require('ramedlawH.nvim-treesitter')
require('ramedlawH.nvim-tree')
require('ramedlawH.bufferline')
require('ramedlawH.lspconfig')
